# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03ef8e1d03c06eac4c42005a0dea08da938413da44ef91d4ae5f710ebe5f50b434f2e8e8ae9d7a1d4e0c176f52b2d7919f8a4a5d63c02c874277f7b76caa7cb5

test:
  secret_key_base: 03d22338360caf0634f7efac41f9c053eb508af7d7300074fb63af946756b01b0e763cf449763f058b55ba462c0a142a45dccea496ac1594c27893edd0b4df36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
